.TH SPYDR 1 "2008 January 02"
.UC 4
.SH NAME
spydr \- GUI for Image display and analysis with yorick
.SH SYNOPSIS
.TP 2
Spydr can be invoqued from the shell
.B spydr
[ options ]
.I image1.fits
[ image2.fits ... ]
.br
where the fits images can contain single images (not necessarily of
the same size) or data cube. Widlcards are allowed in names.
.TP 3
or within yorick
.B #include "spydr.i"
.br
.B spydr,im1,im2,cube
.br
.B spydr,"image1.fits",...
.SH COMMAND LINE OPTIONS
.TP
.BI --conf\ file
configuration file.
.TP
.BI --dpi\ value
Yorick dpi value (yorick default = 75, spydr default = 83). Any value
between 30 and 150 make sense.
.TP
.BI --itt\ value
Intensity Transfer Table (1=linear, 2=sqrt, 3=square, 4=log)
.TP
.BI --pixsize\ value
Pixel size (or plate scale) in arcsec.
.TP
.BI --boxsize\ value
Radius of box for PSF fitting
.TP
.BI --saturation\ value
Value above which pixels have to be considered as saturated (ADU)
.TP
.BI --wavelength\ value
Force wavelength for all images
.TP
.BI --zeropoint\ value
Photometric zeropoint (magnitude)
.TP
.BI --nbins\ value
Number of bins for histograms
.TP
.BI --strehlmask\ value
Radius of circular mask for Strehl calculations
.TP
.BI --debug
Turn on the verbose mode (debugging mode).
.TP
.BI --invert
Invert LUT
.TP
.BI --fullgui
Show the plugin pane when the GUI is realized
.TP
.BI --compact
Hide the lower part of the GUI at startup
.SH DESCRIPTION
.I Spydr
is a GUI for image visualization and simple analysis (cuts, zoom,
values, statistics, histogram, sigma filter) with changeable LUT and
ITT. Spydr has a couple of plugins to measure FWHM and Strehl. Press
"?" on the main display area to get a popup help:

The following shortcuts are available:
 x/y: Plot line/column under cursor
 X/Y: Toggle continuous plot of line/column
       under cursor
 c:   Interactive plot of cut across image
 h:   Plot histogram of visible region
 r:   Radial plot centered on cursor
 f:   Fit 1d gaussian to 1d plot
 e:   Adjust min and max cut to 10% and 99.9% 
      of distribution
 E:   Reset min and max cut to min and max 
      of visible region
 n/p: Next/prevous image
 s:   Sigma filter displayed image
 -/+: Decrease/Increase zoom factor in zoom window
 ?:   This help

.SH EXAMPLES
 From the shell:
 $ spydr --dpi 74 --fullgui 20070730_2*.fits
 $ spydr --pixsize 0.127 20070730_2[2-3]?.fits 20070730_241.fits

 Within yorick:
 > spydr,"~/ascam/2007jun26/20070625T2000*.fits"
 > spydr,["20070730_1[1-3].fits","20070730_23.fits"]
 > spydr,image
 > spydr,[im1,im2]
 > spydr,im1,im2

.SH ENVIRONMENT VARIABLES

.TP
.BI Y_PYTHON
Force the path to spydr.py. The default path is

.B ./:Y_USER:Y_USER/python/:Y_SITES/python/:Y_SITE/python/
.TP
.BI Y_GLADE
Force the path to spydr.glade. The default path is

.B ./:Y_USER:Y_USER/glade/:Y_SITES/glade/:Y_SITE/glade/
.TP
.BI Y_CONF
Force the path to spydr.conf. The default path is

.B ./:Y_USER:Y_SITE:/etc/:
.br
.B ./share/:Y_USER/share/:Y_SITE/share/:
.br
.B ./share/spydr/:Y_USER/share/spydr/:Y_SITE/share/spydr/


.SH RESTRICTIONS AND BUGS

 - only fits images handled to date
 - the ITT display is not very well handled

.SH AUTHOR
.PP
Francois Rigaut, Gemini Observatory
.PP
.SH FILES
.PP
Input files:
.TP 12
spydr.conf
The spydr configuration file. Needed. It should have come with your
installation. The routine which_spydrconf() returns the path to the
used spydr.conf. The following directories are searched for
spydr.conf, in this order:
Y_USER, Y_SITE, /etc, Y_USER/share, Y_SITE/share, Y_USER/share/spydr,
Y_SITE/share/spydr. If you wish to modify the defaults, copy the file
over to Y_USER and modify at will. 
.PP
Output files: none.
.SH SEE ALSO
yorick(1), yao(1)
